name: moxis-dotnet-test
description: 'Run Moxis .NET tests'

inputs:
  dotnet-version:
    description: 'The .NET version to use'
    required: false
    default: '10.x'
  timezone:
    description: 'Timezone for test execution (default: UTC)'
    required: false
    default: 'UTC'
  
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v6
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Restore dependencies
      shell: bash
      run: |
        dotnet restore --locked-mode
    - name: Run tests
      shell: bash
      env:
        TZ: ${{ inputs.timezone || 'UTC' }}
      run: |
        dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results/test-results.trx" --results-directory test-results
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: |
          test-results/test-results/test-results.trx